apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "access-controller.fullname" . }}-config
  labels:
    {{- include "access-controller.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcGateway:
      enabled: {{ .Values.grpcGateway.enabled }}
    cockroachdb:
      host: {{ include "access-controller.databaseHost" . | quote }}
      port: {{ include "access-controller.databasePort" . | quote }}
      database: {{ include "access-controller.databaseName" . | quote }}
