{{- if .Values.watcher.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authorizer.watcher.fullname" . }}-config
  labels:
    {{- include "authorizer.watcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcGateway:
      enabled: {{ .Values.watcher.grpcGateway.enabled }}
    cockroachdb:
      host: {{ include "authorizer.databaseHost" . | quote }}
      port: {{ include "authorizer.databasePort" . | quote }}
      database: {{ include "authorizer.databaseName" . | quote }}
---
{{- end }}