{{- if .Values.watcher.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "authorizer.watcher.fullname" . }}
  labels:
    {{- include "authorizer.watcher.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "authorizer.watcher.fullname" . }}
  minReplicas: {{ .Values.watcher.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.watcher.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.watcher.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.watcher.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.watcher.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.watcher.autoscaling.targetMemory }}
    {{- end }}
---
{{- end }}
