{{- if .Values.watcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authorizer.watcher.fullname" . }}
  labels:
    {{- include "authorizer.watcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.watcher.service.ports.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.watcher.grpcGateway.enabled }}
    - port: {{ .Values.watcher.service.ports.grpcGateway.port }}
      targetPort: grpc-gateway
      protocol: TCP
      name: grpc-gateway
    {{- end }}
  selector:
    {{- include "authorizer.watcher.selectorLabels" . | nindent 4 }}
---
{{- end }}