apiVersion: v2
name: authorizer
description: A Helm chart for the Authorizer platform - the scalable, flexible, and fast application permission management platform.
type: application
version: 0.1.0
kubeVersion: ">= 1.12.0"
keywords:
- iam
- authorization
- authorizer
- access-control
- access-management
- zanzibar
dependencies:
- name: access-controller
  version: "0.1.2"
  repository: https://authorizer-tech.github.io/helm-charts/
