{{- if .Values.cockroachdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "access-controller.fullname" . }}
  labels:
    {{- include "access-controller.labels" . | nindent 4 }}
type: Opaque
data:
  cockroachdb-password: {{ .Values.cockroachdb.auth.password | b64enc | quote }}
{{- end }}